### PR TITLE
fix VCOMPOSE-1516

### PR DESCRIPTION
**Pull request by andreaturli**
@aledsage can you please take a look?

### CODE REVIEW

**Comment by andreaturli** [comment]
@aledsage I think the failure is due to an old brooklyn SNAPSHOT available on the apache repos.

**Comment by nakomis** [comment]
Tested, LGTM

**Comment by nakomis** [comment]
LGTM, basic test done, testing latest changes (i.e. specifying port)

**Comment by aledsage** [comment]
See comments in https://github.com/brooklyncentral/advanced-networking/pull/63, which builds on this PR. I reviewed your code in that one instead of here.

**Pull request merged**
